site_name: slp Documentation
theme: material
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  version:
    provider: mike

nav:
    - 'index.md'
    - 'get-started.md'
    - 'tuning.md'
    - 'config.md'
    - 'data-utils.md'
    - 'plbind.md'
    - 'modules.md'
    - 'multimodal.md'
    - 'utils.md'
    - 'apiref.md'
